[package]
name = "zkdvrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
halo2wrong = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", tag = "v2023_04_20"}
halo2_gadgets = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_04_20"}
halo2_ecc ={ package = "ecc", git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", tag = "v2023_04_20"}
halo2_maingate =  { package = "maingate", git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", tag = "v2023_04_20"}
ark-std = { version = "0.3", features = ["print-trace"] }
sha3 = "0.9.1"
rand_core = { version = "0.6", default-features = false }

static_assertions = "1.1.0"
subtle = "2.4"
blake2b_simd = "1"

[dev-dependencies]
rand_chacha = "0.3.1"